[build]
  publish = "/"  # The directory to deploy (root in this case)
  command = ""     # No build command needed for static site

# Basic redirect support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://api.fontshare.com https://fonts.googleapis.com https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://api.fontshare.com https://fonts.googleapis.com; img-src 'self' data: https://ui-avatars.com; font-src 'self' https://cdnjs.cloudflare.com https://api.fontshare.com https://fonts.gstatic.com; connect-src 'self' https://api.fontshare.com;"
