[build]
  publish = "/"  # The directory to deploy (root in this case)
  command = ""     # No build command needed for static site

# Basic redirect support - SPA support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        https://cdnjs.cloudflare.com 
        https://api.fontshare.com 
        https://fonts.googleapis.com 
        https://fonts.gstatic.com;
      style-src 'self' 'unsafe-inline' 
        https://cdnjs.cloudflare.com 
        https://api.fontshare.com 
        https://fonts.googleapis.com;
      img-src 'self' data: 
        https://ui-avatars.com 
        https://*.cloudinary.com 
        https://*.google-analytics.com 
        https://*.google.com;
      font-src 'self' 
        https://cdnjs.cloudflare.com 
        https://api.fontshare.com 
        https://fonts.gstatic.com;
      connect-src 'self' 
        https://api.fontshare.com 
        https://*.google-analytics.com;
      frame-src 'self' 
        https://www.youtube.com 
        https://www.google.com;
      """.replace(/\s+/g, ' ').trim()
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"
    Feature-Policy = "geolocation 'none'; microphone 'none'; camera 'none'"
    
    # Additional security headers
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # CORS headers
    Access-Control-Allow-Origin = "*"

# Cache control for static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Sitemap and robots.txt
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

# Security headers for HTML pages
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Security-Policy-Report-Only = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self'"

# Redirect www to non-www
[[redirects]]
  from = "https://www.yourdomain.com/*"
  to = "https://yourdomain.com/:splat"
  status = 301
  force = true
